### ISSUE TITLE
Banner MOTD - Parser error

### ISSUE THREAD

**Issue by netjflo** [tdorssers/ztp#2]
Banner MOTD fails to configure from both the "CLI" or "template" methods available in this script. The failed to parse error occurs after the banner motd command, when the first line of the motd is entered. Is this not something the script supports?

```
CLI Method:
switch# banner motd ^ <--- No error

Banner Text  <-- Failed to parse error
Banner Text  <-- Failed to Parse error

^            <-- Failed to Parse error
```
```

Template Method:
switch# banner motd ^ <--- No error

$bannerline1        <-- Failed to parse error
$bannerline2        <-- Failed to parse error

^                   <-- Failed to parse error
```

**Comment by tdorssers** [comment]
Are you using the Python or TCL script?

**Comment by netjflo** [comment]
> Are you using the Python or TCL script?

I'm using the Python script.

**Comment by tdorssers** [comment]
cli.configure() of ZTP does not support multi-line banner configurations. I have added the limitation to README.md.
